# Data and results
result_dir: "./results"
data_loading_arguments:
  use_curated_dataset: false  # the dataset from 2024 with 50 samples
  remove_samples_without_label: false
  sample_small_dataset: true
  min_samples_per_class: 7  # only used is sample_small_dataset is true
