# Data and results
result_dir: "./results"
data_loading_arguments:
  use_curated_dataset: True
  sample_small_dataset: False
  remove_samples_without_label: False
  input_label_key_map:
    Anonymised letter: input_text
    Label_student: label
  label_value_map:
    No FU: null
    No FU yet: null
