# Data and results
result_dir: "./results"
data_loading_arguments:
  use_curated_dataset: false  # the dataset from 2024 with 50 samples
  remove_samples_without_label: true
  sample_small_dataset: true
  min_samples_per_class: 10  # for small sample dataset
