
# Data and results
RESULT_DIR: "./results"
DATASET_PATH: ".data/data_2025/processed/dataset.csv"

# Model configuration
MODEL_PATH: unsloth/Qwen3-8B-GGUF
QUANT_METHOD: gguf
QUANT_SCHEME: Q4_K_M
MAX_CONTEXT_LENGTH: 16384  # note: maximum tokens in a "lettre de sortie" is 6144
MAX_GENERATED_TOKENS: 1024
TOP_P: 0.95
TEMPERATURE: 0.80
USE_FLASH_ATTENTION: True

# Run parameters
N_INFERENCE_REPEATS: 10  # number of times each inference is repeated for benchmark
INFERENCE_BACKEND: "hf"  # hf, vllm, llama-cpp
USE_OUTPUT_GUIDE: True
SKIP_TO_NEXT_MODEL_IF_ERROR: True
DELETE_MODEL_CACHE_AFTER_RUN: True
