output_schema_name: PatientInfoSchema
output_schema_dict:
  # description:  # TODO: IGNORE IF REASONING MODEL, KEEP IF NOT (SEE PROMPT_CONFIG ALSO)
  #   title: Description
  #   type: string
  #   description: Eléments permettant de déterminer le score mRS du patient.
  #   default: Not extracted
  #   maxLength: 512
  mRS:
    title: Score mRS
    type: integer
    description: Score sur l'échelle de Rankin Modifiée (0-6)
    default: -1
    minimum: 0
    maximum: 6
  # /!\ OTHER EXAMPLES (SPECIFIC) /!\
  # visit_date:
  #   type: string  # mapped to python type "str"
  #   description: Date au format jj/mm/aaaa
  #   pattern: ^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$  # note: backslash escaped
  # /!\ OTHER EXAMPLES (GENERAL) /!\
  # completion_ratio:
  #   type: number  # mapped to python type "float"
  #   description: "Ratio of completion, must be between 0 and 1 (exclusive)
  #   exclusiveMinimum: 0.0  # mapped to pydantic "gt"
  #   exclusiveMaximum: 1.0  # mapped to pydantic "lt"
  # items_processed:
  #   type: array  # mapped to python type "list"
  #   description: "List of processed item IDs."
  #   items:
  #     type: integer
  #     minimum: 0  # mapped to pydantic "ge"
  #     maximum: 1000  # mapped to pydantic "le"
  #   minItems: 0  # mapped to pydantic "min_length" for lists
  #   maxItems: 10  # mapped to pydantic "max_length" for lists