output_schema_name: PatientInfoSchema
output_schema:
  reasoning:
    title: Reasoning
    type: string  # mapped to python type "str"
    description: Le raisonnement du modèle pour déterminer le score mRS.
    default: Reasoning not extracted
    constraints:
      maxLength: 512  # mapped to pydantic "max_length"
  mRS:
    title: mRS score
    type: integer  # mapped to python type "int"
    description: Échelle de Rankin Modifiée (0-6)
    default: -1
    constraints:
      minimum: 0  # mapped to pydantic "ge"
      maximum: 6  # mapped to pydantic "le"
  # visit_date:
  #   type: string  # mapped to python type "str"
  #   description: Date au format jj/mm/aaaa
  #   constraints:
  #     pattern: ^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$  # note: backslash escaped
  # /!\ OTHER EXAMPLES /!\
  # completion_ratio:
  #   type: number  # mapped to python type "float"
  #   description: "Ratio of completion, must be between 0 and 1 (exclusive)
  #   constraints:
  #     exclusiveMinimum: 0.0  # mapped to pydantic "gt"
  #     exclusiveMaximum: 1.0  # mapped to pydantic "lt"
  # items_processed:
  #   type: array  # mapped to python type "list"
  #   description: "List of processed item IDs."
  #   items:
  #     type: integer
  #     constraints:
  #       minimum: 0  # mapped to pydantic "ge"
  #       maximum: 1000  # mapped to pydantic "le"
  #   constraints:
  #     minItems: 0  # mapped to pydantic "min_length" for lists
  #     maxItems: 10  # mapped to pydantic "max_length" for lists